export default {
  home: "/",
  exchange: "/#exchange",
  recent_exchange: "/#recent-exchange",
  exchange_details: "/exchange-details",
  rates: "/rates",
  reviews: "/#reviews",
  terms_of_service: "/terms-of-service",
  privacy_policy: "/privacy-policy",
  about_us: "/about-us",
  faq: "/faq",
  news: "/news",
  customer_reviews: "/#reviews",
  affiliate: "/affiliate-program",
  login: "/login",
  create_account: "/register",
  reset_password: "/reset-password",
  profile: "/profile",
  admin: {
    dashboard: "/admin",
    exchange: "/admin/exchange",
    rates: "/admin/rates",
    reviews: "/admin/reviews",
    referrals: "/admin/referrals",
    profile: "/admin/profile",
    notFound: "/admin/*",
  },
  notFound: "*",
};
